- name: Install zsh
  package:
    name: zsh
    state: present

- name: Set zsh as shell as default
  user:
    name: "{{username}}"
    state: present
    shell: /bin/zsh

- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{username}}/.oh-my-zsh"
    depth: 1
  become: yes
  become_user: "{{username}}"

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{username}}/.oh-my-zsh/plugins/zsh-autosuggestions"
    depth: 1
  become: yes
  become_user: "{{username}}"

- name: Copy .zshrc config to user directory
  copy:
    src: "{{ role_path }}/files/.zshrc"
    dest: "/home/{{username}}/.zshrc"
    owner: "{{username}}"
    group: "{{username}}"
    force: no
