- name: Import microsoft public key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF

- name: Add azure-cli repository
  apt_repository:
    filename: azure-cli
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli {{ubuntu_release_name}} main"
    state: present

- name: Install azure-cli
  package:
    name: azure-cli
    state: present
