- name: Install docker dependencies
  package:
    name: "{{item}}"
    state: present
  with_items:
   - gnupg-agent

- name: Import docker public key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add docker repository
  apt_repository:
    filename: docker-ce
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ubuntu_release_name}} stable"
    state: present

- name: Install docker ce
  package:
    name: "{{item}}"
    state: present
  with_items:
   - docker-ce
   - docker-ce-cli
   - containerd.io
   - docker-compose

- name: Add user "{{ username }}" to group docker
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
