- name: Create diretory for jetbrains toolbox
  file:
    path: /opt/jetbrains
    state: directory
    mode: 0755
    owner: "{{username}}"
    group: "{{username}}"

- name: Download and unpack jetbrains toolbox
  unarchive:
    src: "https://download-cf.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz"
    creates: /opt/jetbrains/jetbrains-toolbox
    remote_src: yes
    dest: /opt/jetbrains
    extra_opts:
      - "--strip-components=1"
  become: yes
  become_user: "{{username}}"
