- name: Create diretory for jmeter
  file:
    path: /opt/jmeter
    state: directory
    mode: 0755
    owner: "{{username}}"
    group: "{{username}}"

- name: Download and unpack jmeter
  unarchive:
    src: "https://ftp.halifax.rwth-aachen.de/apache//jmeter/binaries/apache-jmeter-{{jmeter_version}}.tgz"
    creates: /opt/jmeter/bin/jmeter
    remote_src: yes
    dest: /opt/jmeter
    extra_opts:
      - "--strip-components=1"
  become: yes
  become_user: "{{username}}"

- name: Create jmeter link
  file:
    src: /opt/jmeter/bin/jmeter
    dest: "/home/{{username}}/.local/bin/jmeter"
    state: link
