- name: Create diretory for k9s
  file:
    path: /opt/k9s
    state: directory
    mode: 0755
    owner: "{{username}}"
    group: "{{username}}"

- name: Download and unpack k9s
  unarchive:
    src: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_x86_64.tar.gz"
    creates: /opt/k9s/k9s
    remote_src: yes
    dest: /opt/k9s
  become: yes
  become_user: "{{username}}"
