- name: Check if slack is already installed
  stat:
    path: /usr/bin/slack
  register: slack_alias

- name: Install slack
  apt:
    deb: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{slack_version}}-amd64.deb"
    state: present
  when: slack_alias.stat.exists == False
