- name: Import virtualbox public key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
    id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF

- name: Add virtualbox repository
  apt_repository:
    filename: virtualbox
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ubuntu_release_name}} contrib"
    state: present

- name: Install virtualbox dependencies
  package:
    name: "{{item}}"
    state: present
  with_items:
   - "linux-headers-{{ ansible_kernel }}"
   - dkms
   - "virtualbox-{{ virtualbox_version }}"

- name: Add user "{{ username }}" to group vboxusers
  user:
    name: "{{ username }}"
    groups: vboxusers
    append: yes
